// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "antd/dist/reset.css"; // Import Ant Design styles
import "./globals.css"; // Your global styles (including Tailwind CSS)

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
